//! Deterministic code generation of `src/generated_manifest.rs`.
//!
//! The output contains zero environment metadata (no hosts, no timestamps):
//! regenerating from identical verdict sets is byte-identical across
//! machines, keeping the CI `git diff --exit-code` drift check meaningful.
//! Host enums are validated in memory only.

/// Escape a Rust string literal for codegen (glyphs are single ASCII/Unicode
/// chars; fallbacks are plain ASCII).
fn rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// One manifest entry ready for emission.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    /// Catalog id, e.g. `box_2502`.
    pub id: String,
    pub codepoint: u32,
    /// Module name, e.g. `box_drawing`.
    pub module: String,
    /// Constant name, e.g. `BOX_2502`.
    pub const_name: String,
    pub glyph: char,
    pub fallback: &'static str,
}

impl Entry {
    #[must_use]
    pub fn new(
        id: String,
        codepoint: u32,
        module: String,
        const_name: String,
        glyph: char,
        fallback: &'static str,
    ) -> Self {
        Self {
            id,
            codepoint,
            module,
            const_name,
            glyph,
            fallback,
        }
    }
}

/// Render the full manifest source. Entries must already be sorted by
/// codepoint; this function performs no reordering beyond stable grouping.
#[must_use]
pub fn generate(entries: &[Entry]) -> String {
    let mut out = String::with_capacity(entries.len() * 96 + 4096);
    out.push_str("// @generated by manifest-gen — DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str("// Every entry passed the dual-pass verification pipeline (PTY cursor\n");
    out.push_str("// assertions + pixel-level screenshot assertions) on ALL supported\n");
    out.push_str("// platform default terminals simultaneously (the CI AND gate).\n");
    // Keep rustfmt away from generated output: the CI drift check compares
    // this file byte-for-byte against fresh generator output. The skip lives
    // on the `mod generated_manifest` declaration in lib.rs (inner tool
    // attributes are unstable for non-root modules).
    out.push_str("use crate::SafeIcon;\n\n");

    // Master slice.
    if entries.is_empty() {
        out.push_str("pub static UNIVERSAL_ICONS: &[SafeIcon] = &[];\n");
    } else {
        out.push_str("pub static UNIVERSAL_ICONS: &[SafeIcon] = &[\n");
        for e in entries {
            out.push_str(&format!("    {},\n", master_expr(e)));
        }
        out.push_str("];\n");
    }

    // Per-block modules with named constants.
    for module in ["ascii", "box_drawing", "block_elements", "braille"] {
        let group: Vec<&Entry> = entries.iter().filter(|e| e.module == module).collect();
        out.push('\n');
        out.push_str(&format!("pub mod {module} {{\n"));
        out.push_str("    use crate::SafeIcon;\n");
        for e in group {
            out.push_str(&format!(
                "    pub const {}: SafeIcon = SafeIcon::new({}, {});\n",
                e.const_name,
                rust_str(&e.glyph.to_string()),
                rust_str(e.fallback),
            ));
        }
        out.push_str("}\n");
    }

    // lookup() by catalog id.
    out.push_str("\n/// Look up a verified icon by its catalog id (e.g. `\"box_2502\"`).\n");
    out.push_str("#[must_use]\npub fn lookup(id: &str) -> Option<SafeIcon> {\n");
    if entries.is_empty() {
        out.push_str("    None\n");
    } else {
        out.push_str("    match id {\n");
        for e in entries {
            out.push_str(&format!(
                "        {:<24} Some({}),\n",
                format!("{:?} =>", e.id),
                master_expr(e),
            ));
        }
        out.push_str("        _ => None,\n");
        out.push_str("    }\n");
    }
    out.push_str("}\n");

    // by_codepoint().
    out.push_str("\n/// Look up a verified icon by its glyph codepoint.\n");
    out.push_str("#[must_use]\npub fn by_codepoint(c: char) -> Option<&'static SafeIcon> {\n");
    out.push_str("    UNIVERSAL_ICONS.iter().find(|icon| icon.glyph.starts_with(c))\n}\n");

    out
}

fn master_expr(e: &Entry) -> String {
    format!("{}::{}", e.module, e.const_name)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_entries() -> Vec<Entry> {
        vec![
            Entry::new(
                "ascii_0021".into(),
                0x21,
                "ascii".into(),
                "ASCII_0021".into(),
                '!',
                "!",
            ),
            Entry::new(
                "box_2502".into(),
                0x2502,
                "box_drawing".into(),
                "BOX_2502".into(),
                '\u{2502}',
                "|",
            ),
        ]
    }

    #[test]
    fn output_is_deterministic() {
        let a = generate(&sample_entries());
        let b = generate(&sample_entries());
        assert_eq!(a, b);
        assert_eq!(a, generate(&sample_entries()));
    }

    #[test]
    fn empty_manifest_is_valid_rust_shape() {
        let src = generate(&[]);
        assert!(src.contains("UNIVERSAL_ICONS: &[SafeIcon] = &[]"));
        assert!(src.contains("None"));
    }

    #[test]
    fn no_environment_metadata_in_output() {
        let src = generate(&sample_entries());
        for banned in [
            "conhost",
            "wt\"",
            "xterm",
            "terminal-app",
            "timestamp",
            "host",
        ] {
            assert!(
                !src.to_ascii_lowercase().contains(banned),
                "leaked: {banned}"
            );
        }
    }

    #[test]
    fn entries_render_as_expected() {
        let src = generate(&sample_entries());
        assert!(src.contains("pub mod box_drawing {"));
        assert!(src.contains("pub const BOX_2502: SafeIcon = SafeIcon::new(\"│\", \"|\");"));
        assert!(src.contains("\"ascii_0021\" =>"));
        assert!(src.contains("=> Some(ascii::ASCII_0021)".trim_start_matches("=> ")));
        assert!(src.contains("Some(ascii::ASCII_0021)"));
    }
}
