// @generated by manifest-gen — DO NOT EDIT.
//
// Every entry passed the dual-pass verification pipeline (PTY cursor
// assertions + pixel-level screenshot assertions) on ALL supported
// platform default terminals simultaneously (the CI AND gate).
use crate::SafeIcon;

pub static UNIVERSAL_ICONS: &[SafeIcon] = &[
    ascii::ASCII_0021,
    ascii::ASCII_0022,
    ascii::ASCII_0027,
    ascii::ASCII_0028,
    ascii::ASCII_0029,
    ascii::ASCII_002C,
    ascii::ASCII_002E,
    ascii::ASCII_002F,
    ascii::ASCII_003A,
    ascii::ASCII_003B,
    ascii::ASCII_003E,
    ascii::ASCII_003F,
    ascii::ASCII_0049,
    ascii::ASCII_004A,
    ascii::ASCII_005B,
    ascii::ASCII_005C,
    ascii::ASCII_005D,
    ascii::ASCII_005E,
    ascii::ASCII_0060,
    ascii::ASCII_0061,
    ascii::ASCII_0063,
    ascii::ASCII_006A,
    ascii::ASCII_0073,
    ascii::ASCII_0074,
    ascii::ASCII_007A,
    ascii::ASCII_007B,
    ascii::ASCII_007C,
    ascii::ASCII_007D,
    arrows::ARROW_21A8,
    box_drawing::BOX_2502,
    box_drawing::BOX_2503,
    box_drawing::BOX_2506,
    box_drawing::BOX_2507,
    box_drawing::BOX_250A,
    box_drawing::BOX_250B,
    box_drawing::BOX_2510,
    box_drawing::BOX_2511,
    box_drawing::BOX_2512,
    box_drawing::BOX_2513,
    box_drawing::BOX_2518,
    box_drawing::BOX_2519,
    box_drawing::BOX_251A,
    box_drawing::BOX_251B,
    box_drawing::BOX_2524,
    box_drawing::BOX_2525,
    box_drawing::BOX_2526,
    box_drawing::BOX_2527,
    box_drawing::BOX_2528,
    box_drawing::BOX_2529,
    box_drawing::BOX_252A,
    box_drawing::BOX_252B,
    box_drawing::BOX_254E,
    box_drawing::BOX_254F,
    box_drawing::BOX_2551,
    box_drawing::BOX_2555,
    box_drawing::BOX_2556,
    box_drawing::BOX_2557,
    box_drawing::BOX_255B,
    box_drawing::BOX_255C,
    box_drawing::BOX_255D,
    box_drawing::BOX_2561,
    box_drawing::BOX_2562,
    box_drawing::BOX_2563,
    box_drawing::BOX_256E,
    box_drawing::BOX_256F,
    box_drawing::BOX_2574,
    box_drawing::BOX_2575,
    box_drawing::BOX_2577,
    box_drawing::BOX_2578,
    box_drawing::BOX_2579,
    box_drawing::BOX_257B,
    box_drawing::BOX_257D,
    box_drawing::BOX_257F,
    block_elements::BLOCK_258C,
    geometric_shapes::GEOMETRIC_25AA,
    geometric_shapes::GEOMETRIC_25AB,
    geometric_shapes::GEOMETRIC_25B4,
    geometric_shapes::GEOMETRIC_25B8,
    geometric_shapes::GEOMETRIC_25BE,
    geometric_shapes::GEOMETRIC_25C2,
    misc_symbols::MISC_2607,
    misc_symbols::MISC_2613,
    misc_symbols::MISC_2628,
    misc_symbols::MISC_263E,
    misc_symbols::MISC_263F,
    misc_symbols::MISC_2644,
    misc_symbols::MISC_2647,
    misc_symbols::MISC_266D,
    misc_symbols::MISC_266F,
    dingbats::DINGBAT_2758,
    dingbats::DINGBAT_2759,
    dingbats::DINGBAT_275A,
    dingbats::DINGBAT_2761,
    dingbats::DINGBAT_27A7,
    braille::BRAILLE_2801,
    braille::BRAILLE_2802,
    braille::BRAILLE_2803,
    braille::BRAILLE_2804,
    braille::BRAILLE_2805,
    braille::BRAILLE_2806,
    braille::BRAILLE_2807,
    braille::BRAILLE_2840,
    braille::BRAILLE_2841,
    braille::BRAILLE_2842,
    braille::BRAILLE_2843,
    braille::BRAILLE_2844,
    braille::BRAILLE_2845,
    braille::BRAILLE_2846,
    braille::BRAILLE_2847,
    braille::BRAILLE_2880,
    braille::BRAILLE_2881,
    braille::BRAILLE_2882,
    braille::BRAILLE_2883,
    braille::BRAILLE_2884,
    braille::BRAILLE_2885,
    braille::BRAILLE_2886,
    braille::BRAILLE_2887,
    braille::BRAILLE_28C0,
    braille::BRAILLE_28C1,
    braille::BRAILLE_28C2,
    braille::BRAILLE_28C3,
    braille::BRAILLE_28C4,
    braille::BRAILLE_28C5,
    braille::BRAILLE_28C6,
    braille::BRAILLE_28C7,
];

pub mod ascii {
    use crate::SafeIcon;
    pub const ASCII_0021: SafeIcon = SafeIcon::new("!", "");
    pub const ASCII_0022: SafeIcon = SafeIcon::new("\"", "");
    pub const ASCII_0027: SafeIcon = SafeIcon::new("'", "");
    pub const ASCII_0028: SafeIcon = SafeIcon::new("(", "");
    pub const ASCII_0029: SafeIcon = SafeIcon::new(")", "");
    pub const ASCII_002C: SafeIcon = SafeIcon::new(",", "");
    pub const ASCII_002E: SafeIcon = SafeIcon::new(".", "");
    pub const ASCII_002F: SafeIcon = SafeIcon::new("/", "");
    pub const ASCII_003A: SafeIcon = SafeIcon::new(":", "");
    pub const ASCII_003B: SafeIcon = SafeIcon::new(";", "");
    pub const ASCII_003E: SafeIcon = SafeIcon::new(">", "");
    pub const ASCII_003F: SafeIcon = SafeIcon::new("?", "");
    pub const ASCII_0049: SafeIcon = SafeIcon::new("I", "");
    pub const ASCII_004A: SafeIcon = SafeIcon::new("J", "");
    pub const ASCII_005B: SafeIcon = SafeIcon::new("[", "");
    pub const ASCII_005C: SafeIcon = SafeIcon::new("\\", "");
    pub const ASCII_005D: SafeIcon = SafeIcon::new("]", "");
    pub const ASCII_005E: SafeIcon = SafeIcon::new("^", "");
    pub const ASCII_0060: SafeIcon = SafeIcon::new("`", "");
    pub const ASCII_0061: SafeIcon = SafeIcon::new("a", "");
    pub const ASCII_0063: SafeIcon = SafeIcon::new("c", "");
    pub const ASCII_006A: SafeIcon = SafeIcon::new("j", "");
    pub const ASCII_0073: SafeIcon = SafeIcon::new("s", "");
    pub const ASCII_0074: SafeIcon = SafeIcon::new("t", "");
    pub const ASCII_007A: SafeIcon = SafeIcon::new("z", "");
    pub const ASCII_007B: SafeIcon = SafeIcon::new("{", "");
    pub const ASCII_007C: SafeIcon = SafeIcon::new("|", "");
    pub const ASCII_007D: SafeIcon = SafeIcon::new("}", "");
}

pub mod arrows {
    use crate::SafeIcon;
    pub const ARROW_21A8: SafeIcon = SafeIcon::new("↨", "*");
}

pub mod box_drawing {
    use crate::SafeIcon;
    pub const BOX_2502: SafeIcon = SafeIcon::new("│", "|");
    pub const BOX_2503: SafeIcon = SafeIcon::new("┃", "+");
    pub const BOX_2506: SafeIcon = SafeIcon::new("┆", "+");
    pub const BOX_2507: SafeIcon = SafeIcon::new("┇", "+");
    pub const BOX_250A: SafeIcon = SafeIcon::new("┊", "+");
    pub const BOX_250B: SafeIcon = SafeIcon::new("┋", "+");
    pub const BOX_2510: SafeIcon = SafeIcon::new("┐", "+");
    pub const BOX_2511: SafeIcon = SafeIcon::new("┑", "+");
    pub const BOX_2512: SafeIcon = SafeIcon::new("┒", "+");
    pub const BOX_2513: SafeIcon = SafeIcon::new("┓", "+");
    pub const BOX_2518: SafeIcon = SafeIcon::new("┘", "+");
    pub const BOX_2519: SafeIcon = SafeIcon::new("┙", "+");
    pub const BOX_251A: SafeIcon = SafeIcon::new("┚", "+");
    pub const BOX_251B: SafeIcon = SafeIcon::new("┛", "+");
    pub const BOX_2524: SafeIcon = SafeIcon::new("┤", "+");
    pub const BOX_2525: SafeIcon = SafeIcon::new("┥", "+");
    pub const BOX_2526: SafeIcon = SafeIcon::new("┦", "+");
    pub const BOX_2527: SafeIcon = SafeIcon::new("┧", "+");
    pub const BOX_2528: SafeIcon = SafeIcon::new("┨", "+");
    pub const BOX_2529: SafeIcon = SafeIcon::new("┩", "+");
    pub const BOX_252A: SafeIcon = SafeIcon::new("┪", "+");
    pub const BOX_252B: SafeIcon = SafeIcon::new("┫", "+");
    pub const BOX_254E: SafeIcon = SafeIcon::new("╎", "+");
    pub const BOX_254F: SafeIcon = SafeIcon::new("╏", "+");
    pub const BOX_2551: SafeIcon = SafeIcon::new("║", "|");
    pub const BOX_2555: SafeIcon = SafeIcon::new("╕", "+");
    pub const BOX_2556: SafeIcon = SafeIcon::new("╖", "+");
    pub const BOX_2557: SafeIcon = SafeIcon::new("╗", "+");
    pub const BOX_255B: SafeIcon = SafeIcon::new("╛", "+");
    pub const BOX_255C: SafeIcon = SafeIcon::new("╜", "+");
    pub const BOX_255D: SafeIcon = SafeIcon::new("╝", "+");
    pub const BOX_2561: SafeIcon = SafeIcon::new("╡", "+");
    pub const BOX_2562: SafeIcon = SafeIcon::new("╢", "+");
    pub const BOX_2563: SafeIcon = SafeIcon::new("╣", "+");
    pub const BOX_256E: SafeIcon = SafeIcon::new("╮", "+");
    pub const BOX_256F: SafeIcon = SafeIcon::new("╯", "+");
    pub const BOX_2574: SafeIcon = SafeIcon::new("╴", "+");
    pub const BOX_2575: SafeIcon = SafeIcon::new("╵", "+");
    pub const BOX_2577: SafeIcon = SafeIcon::new("╷", "+");
    pub const BOX_2578: SafeIcon = SafeIcon::new("╸", "+");
    pub const BOX_2579: SafeIcon = SafeIcon::new("╹", "+");
    pub const BOX_257B: SafeIcon = SafeIcon::new("╻", "+");
    pub const BOX_257D: SafeIcon = SafeIcon::new("╽", "+");
    pub const BOX_257F: SafeIcon = SafeIcon::new("╿", "+");
}

pub mod block_elements {
    use crate::SafeIcon;
    pub const BLOCK_258C: SafeIcon = SafeIcon::new("▌", "[");
}

pub mod geometric_shapes {
    use crate::SafeIcon;
    pub const GEOMETRIC_25AA: SafeIcon = SafeIcon::new("▪", "#");
    pub const GEOMETRIC_25AB: SafeIcon = SafeIcon::new("▫", "#");
    pub const GEOMETRIC_25B4: SafeIcon = SafeIcon::new("▴", "#");
    pub const GEOMETRIC_25B8: SafeIcon = SafeIcon::new("▸", "#");
    pub const GEOMETRIC_25BE: SafeIcon = SafeIcon::new("▾", "#");
    pub const GEOMETRIC_25C2: SafeIcon = SafeIcon::new("◂", "#");
}

pub mod misc_symbols {
    use crate::SafeIcon;
    pub const MISC_2607: SafeIcon = SafeIcon::new("☇", "*");
    pub const MISC_2613: SafeIcon = SafeIcon::new("☓", "*");
    pub const MISC_2628: SafeIcon = SafeIcon::new("☨", "*");
    pub const MISC_263E: SafeIcon = SafeIcon::new("☾", "*");
    pub const MISC_263F: SafeIcon = SafeIcon::new("☿", "*");
    pub const MISC_2644: SafeIcon = SafeIcon::new("♄", "*");
    pub const MISC_2647: SafeIcon = SafeIcon::new("♇", "*");
    pub const MISC_266D: SafeIcon = SafeIcon::new("♭", "*");
    pub const MISC_266F: SafeIcon = SafeIcon::new("♯", "*");
}

pub mod dingbats {
    use crate::SafeIcon;
    pub const DINGBAT_2758: SafeIcon = SafeIcon::new("❘", "*");
    pub const DINGBAT_2759: SafeIcon = SafeIcon::new("❙", "*");
    pub const DINGBAT_275A: SafeIcon = SafeIcon::new("❚", "*");
    pub const DINGBAT_2761: SafeIcon = SafeIcon::new("❡", "*");
    pub const DINGBAT_27A7: SafeIcon = SafeIcon::new("➧", "*");
}

pub mod braille {
    use crate::SafeIcon;
    pub const BRAILLE_2801: SafeIcon = SafeIcon::new("⠁", "*");
    pub const BRAILLE_2802: SafeIcon = SafeIcon::new("⠂", "*");
    pub const BRAILLE_2803: SafeIcon = SafeIcon::new("⠃", "*");
    pub const BRAILLE_2804: SafeIcon = SafeIcon::new("⠄", "*");
    pub const BRAILLE_2805: SafeIcon = SafeIcon::new("⠅", "*");
    pub const BRAILLE_2806: SafeIcon = SafeIcon::new("⠆", "*");
    pub const BRAILLE_2807: SafeIcon = SafeIcon::new("⠇", "*");
    pub const BRAILLE_2840: SafeIcon = SafeIcon::new("⡀", "*");
    pub const BRAILLE_2841: SafeIcon = SafeIcon::new("⡁", "*");
    pub const BRAILLE_2842: SafeIcon = SafeIcon::new("⡂", "*");
    pub const BRAILLE_2843: SafeIcon = SafeIcon::new("⡃", "*");
    pub const BRAILLE_2844: SafeIcon = SafeIcon::new("⡄", "*");
    pub const BRAILLE_2845: SafeIcon = SafeIcon::new("⡅", "*");
    pub const BRAILLE_2846: SafeIcon = SafeIcon::new("⡆", "*");
    pub const BRAILLE_2847: SafeIcon = SafeIcon::new("⡇", "*");
    pub const BRAILLE_2880: SafeIcon = SafeIcon::new("⢀", "*");
    pub const BRAILLE_2881: SafeIcon = SafeIcon::new("⢁", "*");
    pub const BRAILLE_2882: SafeIcon = SafeIcon::new("⢂", "*");
    pub const BRAILLE_2883: SafeIcon = SafeIcon::new("⢃", "*");
    pub const BRAILLE_2884: SafeIcon = SafeIcon::new("⢄", "*");
    pub const BRAILLE_2885: SafeIcon = SafeIcon::new("⢅", "*");
    pub const BRAILLE_2886: SafeIcon = SafeIcon::new("⢆", "*");
    pub const BRAILLE_2887: SafeIcon = SafeIcon::new("⢇", "*");
    pub const BRAILLE_28C0: SafeIcon = SafeIcon::new("⣀", "*");
    pub const BRAILLE_28C1: SafeIcon = SafeIcon::new("⣁", "*");
    pub const BRAILLE_28C2: SafeIcon = SafeIcon::new("⣂", "*");
    pub const BRAILLE_28C3: SafeIcon = SafeIcon::new("⣃", "*");
    pub const BRAILLE_28C4: SafeIcon = SafeIcon::new("⣄", "*");
    pub const BRAILLE_28C5: SafeIcon = SafeIcon::new("⣅", "*");
    pub const BRAILLE_28C6: SafeIcon = SafeIcon::new("⣆", "*");
    pub const BRAILLE_28C7: SafeIcon = SafeIcon::new("⣇", "*");
}

/// Richer per-icon record for tooling: identity plus official Unicode name.
pub struct IconEntry {
    pub icon: SafeIcon,
    pub id: &'static str,
    pub codepoint: u32,
    pub block: &'static str,
    pub unicode_name: &'static str,
}

/// Metadata for every verified icon, in codepoint order.
pub static ICON_ENTRIES: &[IconEntry] = &[
    IconEntry { icon: ascii::ASCII_0021, id: "ascii_0021", codepoint: 33, block: "ascii", unicode_name: "EXCLAMATION MARK" },
    IconEntry { icon: ascii::ASCII_0022, id: "ascii_0022", codepoint: 34, block: "ascii", unicode_name: "QUOTATION MARK" },
    IconEntry { icon: ascii::ASCII_0027, id: "ascii_0027", codepoint: 39, block: "ascii", unicode_name: "APOSTROPHE" },
    IconEntry { icon: ascii::ASCII_0028, id: "ascii_0028", codepoint: 40, block: "ascii", unicode_name: "LEFT PARENTHESIS" },
    IconEntry { icon: ascii::ASCII_0029, id: "ascii_0029", codepoint: 41, block: "ascii", unicode_name: "RIGHT PARENTHESIS" },
    IconEntry { icon: ascii::ASCII_002C, id: "ascii_002C", codepoint: 44, block: "ascii", unicode_name: "COMMA" },
    IconEntry { icon: ascii::ASCII_002E, id: "ascii_002E", codepoint: 46, block: "ascii", unicode_name: "FULL STOP" },
    IconEntry { icon: ascii::ASCII_002F, id: "ascii_002F", codepoint: 47, block: "ascii", unicode_name: "SOLIDUS" },
    IconEntry { icon: ascii::ASCII_003A, id: "ascii_003A", codepoint: 58, block: "ascii", unicode_name: "COLON" },
    IconEntry { icon: ascii::ASCII_003B, id: "ascii_003B", codepoint: 59, block: "ascii", unicode_name: "SEMICOLON" },
    IconEntry { icon: ascii::ASCII_003E, id: "ascii_003E", codepoint: 62, block: "ascii", unicode_name: "GREATER-THAN SIGN" },
    IconEntry { icon: ascii::ASCII_003F, id: "ascii_003F", codepoint: 63, block: "ascii", unicode_name: "QUESTION MARK" },
    IconEntry { icon: ascii::ASCII_0049, id: "ascii_0049", codepoint: 73, block: "ascii", unicode_name: "LATIN CAPITAL LETTER I" },
    IconEntry { icon: ascii::ASCII_004A, id: "ascii_004A", codepoint: 74, block: "ascii", unicode_name: "LATIN CAPITAL LETTER J" },
    IconEntry { icon: ascii::ASCII_005B, id: "ascii_005B", codepoint: 91, block: "ascii", unicode_name: "LEFT SQUARE BRACKET" },
    IconEntry { icon: ascii::ASCII_005C, id: "ascii_005C", codepoint: 92, block: "ascii", unicode_name: "REVERSE SOLIDUS" },
    IconEntry { icon: ascii::ASCII_005D, id: "ascii_005D", codepoint: 93, block: "ascii", unicode_name: "RIGHT SQUARE BRACKET" },
    IconEntry { icon: ascii::ASCII_005E, id: "ascii_005E", codepoint: 94, block: "ascii", unicode_name: "CIRCUMFLEX ACCENT" },
    IconEntry { icon: ascii::ASCII_0060, id: "ascii_0060", codepoint: 96, block: "ascii", unicode_name: "GRAVE ACCENT" },
    IconEntry { icon: ascii::ASCII_0061, id: "ascii_0061", codepoint: 97, block: "ascii", unicode_name: "LATIN SMALL LETTER A" },
    IconEntry { icon: ascii::ASCII_0063, id: "ascii_0063", codepoint: 99, block: "ascii", unicode_name: "LATIN SMALL LETTER C" },
    IconEntry { icon: ascii::ASCII_006A, id: "ascii_006A", codepoint: 106, block: "ascii", unicode_name: "LATIN SMALL LETTER J" },
    IconEntry { icon: ascii::ASCII_0073, id: "ascii_0073", codepoint: 115, block: "ascii", unicode_name: "LATIN SMALL LETTER S" },
    IconEntry { icon: ascii::ASCII_0074, id: "ascii_0074", codepoint: 116, block: "ascii", unicode_name: "LATIN SMALL LETTER T" },
    IconEntry { icon: ascii::ASCII_007A, id: "ascii_007A", codepoint: 122, block: "ascii", unicode_name: "LATIN SMALL LETTER Z" },
    IconEntry { icon: ascii::ASCII_007B, id: "ascii_007B", codepoint: 123, block: "ascii", unicode_name: "LEFT CURLY BRACKET" },
    IconEntry { icon: ascii::ASCII_007C, id: "ascii_007C", codepoint: 124, block: "ascii", unicode_name: "VERTICAL LINE" },
    IconEntry { icon: ascii::ASCII_007D, id: "ascii_007D", codepoint: 125, block: "ascii", unicode_name: "RIGHT CURLY BRACKET" },
    IconEntry { icon: arrows::ARROW_21A8, id: "arrow_21A8", codepoint: 8616, block: "arrows", unicode_name: "UP DOWN ARROW WITH BASE" },
    IconEntry { icon: box_drawing::BOX_2502, id: "box_2502", codepoint: 9474, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT VERTICAL" },
    IconEntry { icon: box_drawing::BOX_2503, id: "box_2503", codepoint: 9475, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY VERTICAL" },
    IconEntry { icon: box_drawing::BOX_2506, id: "box_2506", codepoint: 9478, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL" },
    IconEntry { icon: box_drawing::BOX_2507, id: "box_2507", codepoint: 9479, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL" },
    IconEntry { icon: box_drawing::BOX_250A, id: "box_250A", codepoint: 9482, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL" },
    IconEntry { icon: box_drawing::BOX_250B, id: "box_250B", codepoint: 9483, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL" },
    IconEntry { icon: box_drawing::BOX_2510, id: "box_2510", codepoint: 9488, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT DOWN AND LEFT" },
    IconEntry { icon: box_drawing::BOX_2511, id: "box_2511", codepoint: 9489, block: "box_drawing", unicode_name: "BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY" },
    IconEntry { icon: box_drawing::BOX_2512, id: "box_2512", codepoint: 9490, block: "box_drawing", unicode_name: "BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT" },
    IconEntry { icon: box_drawing::BOX_2513, id: "box_2513", codepoint: 9491, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY DOWN AND LEFT" },
    IconEntry { icon: box_drawing::BOX_2518, id: "box_2518", codepoint: 9496, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT UP AND LEFT" },
    IconEntry { icon: box_drawing::BOX_2519, id: "box_2519", codepoint: 9497, block: "box_drawing", unicode_name: "BOX DRAWINGS UP LIGHT AND LEFT HEAVY" },
    IconEntry { icon: box_drawing::BOX_251A, id: "box_251A", codepoint: 9498, block: "box_drawing", unicode_name: "BOX DRAWINGS UP HEAVY AND LEFT LIGHT" },
    IconEntry { icon: box_drawing::BOX_251B, id: "box_251B", codepoint: 9499, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY UP AND LEFT" },
    IconEntry { icon: box_drawing::BOX_2524, id: "box_2524", codepoint: 9508, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT VERTICAL AND LEFT" },
    IconEntry { icon: box_drawing::BOX_2525, id: "box_2525", codepoint: 9509, block: "box_drawing", unicode_name: "BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY" },
    IconEntry { icon: box_drawing::BOX_2526, id: "box_2526", codepoint: 9510, block: "box_drawing", unicode_name: "BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT" },
    IconEntry { icon: box_drawing::BOX_2527, id: "box_2527", codepoint: 9511, block: "box_drawing", unicode_name: "BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT" },
    IconEntry { icon: box_drawing::BOX_2528, id: "box_2528", codepoint: 9512, block: "box_drawing", unicode_name: "BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT" },
    IconEntry { icon: box_drawing::BOX_2529, id: "box_2529", codepoint: 9513, block: "box_drawing", unicode_name: "BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY" },
    IconEntry { icon: box_drawing::BOX_252A, id: "box_252A", codepoint: 9514, block: "box_drawing", unicode_name: "BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY" },
    IconEntry { icon: box_drawing::BOX_252B, id: "box_252B", codepoint: 9515, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY VERTICAL AND LEFT" },
    IconEntry { icon: box_drawing::BOX_254E, id: "box_254E", codepoint: 9550, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL" },
    IconEntry { icon: box_drawing::BOX_254F, id: "box_254F", codepoint: 9551, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL" },
    IconEntry { icon: box_drawing::BOX_2551, id: "box_2551", codepoint: 9553, block: "box_drawing", unicode_name: "BOX DRAWINGS DOUBLE VERTICAL" },
    IconEntry { icon: box_drawing::BOX_2555, id: "box_2555", codepoint: 9557, block: "box_drawing", unicode_name: "BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE" },
    IconEntry { icon: box_drawing::BOX_2556, id: "box_2556", codepoint: 9558, block: "box_drawing", unicode_name: "BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE" },
    IconEntry { icon: box_drawing::BOX_2557, id: "box_2557", codepoint: 9559, block: "box_drawing", unicode_name: "BOX DRAWINGS DOUBLE DOWN AND LEFT" },
    IconEntry { icon: box_drawing::BOX_255B, id: "box_255B", codepoint: 9563, block: "box_drawing", unicode_name: "BOX DRAWINGS UP SINGLE AND LEFT DOUBLE" },
    IconEntry { icon: box_drawing::BOX_255C, id: "box_255C", codepoint: 9564, block: "box_drawing", unicode_name: "BOX DRAWINGS UP DOUBLE AND LEFT SINGLE" },
    IconEntry { icon: box_drawing::BOX_255D, id: "box_255D", codepoint: 9565, block: "box_drawing", unicode_name: "BOX DRAWINGS DOUBLE UP AND LEFT" },
    IconEntry { icon: box_drawing::BOX_2561, id: "box_2561", codepoint: 9569, block: "box_drawing", unicode_name: "BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE" },
    IconEntry { icon: box_drawing::BOX_2562, id: "box_2562", codepoint: 9570, block: "box_drawing", unicode_name: "BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE" },
    IconEntry { icon: box_drawing::BOX_2563, id: "box_2563", codepoint: 9571, block: "box_drawing", unicode_name: "BOX DRAWINGS DOUBLE VERTICAL AND LEFT" },
    IconEntry { icon: box_drawing::BOX_256E, id: "box_256E", codepoint: 9582, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT ARC DOWN AND LEFT" },
    IconEntry { icon: box_drawing::BOX_256F, id: "box_256F", codepoint: 9583, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT ARC UP AND LEFT" },
    IconEntry { icon: box_drawing::BOX_2574, id: "box_2574", codepoint: 9588, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT LEFT" },
    IconEntry { icon: box_drawing::BOX_2575, id: "box_2575", codepoint: 9589, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT UP" },
    IconEntry { icon: box_drawing::BOX_2577, id: "box_2577", codepoint: 9591, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT DOWN" },
    IconEntry { icon: box_drawing::BOX_2578, id: "box_2578", codepoint: 9592, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY LEFT" },
    IconEntry { icon: box_drawing::BOX_2579, id: "box_2579", codepoint: 9593, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY UP" },
    IconEntry { icon: box_drawing::BOX_257B, id: "box_257B", codepoint: 9595, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY DOWN" },
    IconEntry { icon: box_drawing::BOX_257D, id: "box_257D", codepoint: 9597, block: "box_drawing", unicode_name: "BOX DRAWINGS LIGHT UP AND HEAVY DOWN" },
    IconEntry { icon: box_drawing::BOX_257F, id: "box_257F", codepoint: 9599, block: "box_drawing", unicode_name: "BOX DRAWINGS HEAVY UP AND LIGHT DOWN" },
    IconEntry { icon: block_elements::BLOCK_258C, id: "block_258C", codepoint: 9612, block: "block_elements", unicode_name: "LEFT HALF BLOCK" },
    IconEntry { icon: geometric_shapes::GEOMETRIC_25AA, id: "geometric_25AA", codepoint: 9642, block: "geometric_shapes", unicode_name: "BLACK SMALL SQUARE" },
    IconEntry { icon: geometric_shapes::GEOMETRIC_25AB, id: "geometric_25AB", codepoint: 9643, block: "geometric_shapes", unicode_name: "WHITE SMALL SQUARE" },
    IconEntry { icon: geometric_shapes::GEOMETRIC_25B4, id: "geometric_25B4", codepoint: 9652, block: "geometric_shapes", unicode_name: "BLACK UP-POINTING SMALL TRIANGLE" },
    IconEntry { icon: geometric_shapes::GEOMETRIC_25B8, id: "geometric_25B8", codepoint: 9656, block: "geometric_shapes", unicode_name: "BLACK RIGHT-POINTING SMALL TRIANGLE" },
    IconEntry { icon: geometric_shapes::GEOMETRIC_25BE, id: "geometric_25BE", codepoint: 9662, block: "geometric_shapes", unicode_name: "BLACK DOWN-POINTING SMALL TRIANGLE" },
    IconEntry { icon: geometric_shapes::GEOMETRIC_25C2, id: "geometric_25C2", codepoint: 9666, block: "geometric_shapes", unicode_name: "BLACK LEFT-POINTING SMALL TRIANGLE" },
    IconEntry { icon: misc_symbols::MISC_2607, id: "misc_2607", codepoint: 9735, block: "misc_symbols", unicode_name: "LIGHTNING" },
    IconEntry { icon: misc_symbols::MISC_2613, id: "misc_2613", codepoint: 9747, block: "misc_symbols", unicode_name: "SALTIRE" },
    IconEntry { icon: misc_symbols::MISC_2628, id: "misc_2628", codepoint: 9768, block: "misc_symbols", unicode_name: "CROSS OF LORRAINE" },
    IconEntry { icon: misc_symbols::MISC_263E, id: "misc_263E", codepoint: 9790, block: "misc_symbols", unicode_name: "LAST QUARTER MOON" },
    IconEntry { icon: misc_symbols::MISC_263F, id: "misc_263F", codepoint: 9791, block: "misc_symbols", unicode_name: "MERCURY" },
    IconEntry { icon: misc_symbols::MISC_2644, id: "misc_2644", codepoint: 9796, block: "misc_symbols", unicode_name: "SATURN" },
    IconEntry { icon: misc_symbols::MISC_2647, id: "misc_2647", codepoint: 9799, block: "misc_symbols", unicode_name: "PLUTO" },
    IconEntry { icon: misc_symbols::MISC_266D, id: "misc_266D", codepoint: 9837, block: "misc_symbols", unicode_name: "MUSIC FLAT SIGN" },
    IconEntry { icon: misc_symbols::MISC_266F, id: "misc_266F", codepoint: 9839, block: "misc_symbols", unicode_name: "MUSIC SHARP SIGN" },
    IconEntry { icon: dingbats::DINGBAT_2758, id: "dingbat_2758", codepoint: 10072, block: "dingbats", unicode_name: "LIGHT VERTICAL BAR" },
    IconEntry { icon: dingbats::DINGBAT_2759, id: "dingbat_2759", codepoint: 10073, block: "dingbats", unicode_name: "MEDIUM VERTICAL BAR" },
    IconEntry { icon: dingbats::DINGBAT_275A, id: "dingbat_275A", codepoint: 10074, block: "dingbats", unicode_name: "HEAVY VERTICAL BAR" },
    IconEntry { icon: dingbats::DINGBAT_2761, id: "dingbat_2761", codepoint: 10081, block: "dingbats", unicode_name: "CURVED STEM PARAGRAPH SIGN ORNAMENT" },
    IconEntry { icon: dingbats::DINGBAT_27A7, id: "dingbat_27A7", codepoint: 10151, block: "dingbats", unicode_name: "SQUAT BLACK RIGHTWARDS ARROW" },
    IconEntry { icon: braille::BRAILLE_2801, id: "braille_2801", codepoint: 10241, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-1" },
    IconEntry { icon: braille::BRAILLE_2802, id: "braille_2802", codepoint: 10242, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-2" },
    IconEntry { icon: braille::BRAILLE_2803, id: "braille_2803", codepoint: 10243, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-12" },
    IconEntry { icon: braille::BRAILLE_2804, id: "braille_2804", codepoint: 10244, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-3" },
    IconEntry { icon: braille::BRAILLE_2805, id: "braille_2805", codepoint: 10245, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-13" },
    IconEntry { icon: braille::BRAILLE_2806, id: "braille_2806", codepoint: 10246, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-23" },
    IconEntry { icon: braille::BRAILLE_2807, id: "braille_2807", codepoint: 10247, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-123" },
    IconEntry { icon: braille::BRAILLE_2840, id: "braille_2840", codepoint: 10304, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-7" },
    IconEntry { icon: braille::BRAILLE_2841, id: "braille_2841", codepoint: 10305, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-17" },
    IconEntry { icon: braille::BRAILLE_2842, id: "braille_2842", codepoint: 10306, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-27" },
    IconEntry { icon: braille::BRAILLE_2843, id: "braille_2843", codepoint: 10307, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-127" },
    IconEntry { icon: braille::BRAILLE_2844, id: "braille_2844", codepoint: 10308, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-37" },
    IconEntry { icon: braille::BRAILLE_2845, id: "braille_2845", codepoint: 10309, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-137" },
    IconEntry { icon: braille::BRAILLE_2846, id: "braille_2846", codepoint: 10310, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-237" },
    IconEntry { icon: braille::BRAILLE_2847, id: "braille_2847", codepoint: 10311, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-1237" },
    IconEntry { icon: braille::BRAILLE_2880, id: "braille_2880", codepoint: 10368, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-8" },
    IconEntry { icon: braille::BRAILLE_2881, id: "braille_2881", codepoint: 10369, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-18" },
    IconEntry { icon: braille::BRAILLE_2882, id: "braille_2882", codepoint: 10370, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-28" },
    IconEntry { icon: braille::BRAILLE_2883, id: "braille_2883", codepoint: 10371, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-128" },
    IconEntry { icon: braille::BRAILLE_2884, id: "braille_2884", codepoint: 10372, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-38" },
    IconEntry { icon: braille::BRAILLE_2885, id: "braille_2885", codepoint: 10373, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-138" },
    IconEntry { icon: braille::BRAILLE_2886, id: "braille_2886", codepoint: 10374, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-238" },
    IconEntry { icon: braille::BRAILLE_2887, id: "braille_2887", codepoint: 10375, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-1238" },
    IconEntry { icon: braille::BRAILLE_28C0, id: "braille_28C0", codepoint: 10432, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-78" },
    IconEntry { icon: braille::BRAILLE_28C1, id: "braille_28C1", codepoint: 10433, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-178" },
    IconEntry { icon: braille::BRAILLE_28C2, id: "braille_28C2", codepoint: 10434, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-278" },
    IconEntry { icon: braille::BRAILLE_28C3, id: "braille_28C3", codepoint: 10435, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-1278" },
    IconEntry { icon: braille::BRAILLE_28C4, id: "braille_28C4", codepoint: 10436, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-378" },
    IconEntry { icon: braille::BRAILLE_28C5, id: "braille_28C5", codepoint: 10437, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-1378" },
    IconEntry { icon: braille::BRAILLE_28C6, id: "braille_28C6", codepoint: 10438, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-2378" },
    IconEntry { icon: braille::BRAILLE_28C7, id: "braille_28C7", codepoint: 10439, block: "braille", unicode_name: "BRAILLE PATTERN DOTS-12378" },
];

/// Look up a verified icon by its catalog id (e.g. `"box_2502"`).
#[must_use]
pub fn lookup(id: &str) -> Option<SafeIcon> {
    match id {
        "ascii_0021" =>          Some(ascii::ASCII_0021),
        "ascii_0022" =>          Some(ascii::ASCII_0022),
        "ascii_0027" =>          Some(ascii::ASCII_0027),
        "ascii_0028" =>          Some(ascii::ASCII_0028),
        "ascii_0029" =>          Some(ascii::ASCII_0029),
        "ascii_002C" =>          Some(ascii::ASCII_002C),
        "ascii_002E" =>          Some(ascii::ASCII_002E),
        "ascii_002F" =>          Some(ascii::ASCII_002F),
        "ascii_003A" =>          Some(ascii::ASCII_003A),
        "ascii_003B" =>          Some(ascii::ASCII_003B),
        "ascii_003E" =>          Some(ascii::ASCII_003E),
        "ascii_003F" =>          Some(ascii::ASCII_003F),
        "ascii_0049" =>          Some(ascii::ASCII_0049),
        "ascii_004A" =>          Some(ascii::ASCII_004A),
        "ascii_005B" =>          Some(ascii::ASCII_005B),
        "ascii_005C" =>          Some(ascii::ASCII_005C),
        "ascii_005D" =>          Some(ascii::ASCII_005D),
        "ascii_005E" =>          Some(ascii::ASCII_005E),
        "ascii_0060" =>          Some(ascii::ASCII_0060),
        "ascii_0061" =>          Some(ascii::ASCII_0061),
        "ascii_0063" =>          Some(ascii::ASCII_0063),
        "ascii_006A" =>          Some(ascii::ASCII_006A),
        "ascii_0073" =>          Some(ascii::ASCII_0073),
        "ascii_0074" =>          Some(ascii::ASCII_0074),
        "ascii_007A" =>          Some(ascii::ASCII_007A),
        "ascii_007B" =>          Some(ascii::ASCII_007B),
        "ascii_007C" =>          Some(ascii::ASCII_007C),
        "ascii_007D" =>          Some(ascii::ASCII_007D),
        "arrow_21A8" =>          Some(arrows::ARROW_21A8),
        "box_2502" =>            Some(box_drawing::BOX_2502),
        "box_2503" =>            Some(box_drawing::BOX_2503),
        "box_2506" =>            Some(box_drawing::BOX_2506),
        "box_2507" =>            Some(box_drawing::BOX_2507),
        "box_250A" =>            Some(box_drawing::BOX_250A),
        "box_250B" =>            Some(box_drawing::BOX_250B),
        "box_2510" =>            Some(box_drawing::BOX_2510),
        "box_2511" =>            Some(box_drawing::BOX_2511),
        "box_2512" =>            Some(box_drawing::BOX_2512),
        "box_2513" =>            Some(box_drawing::BOX_2513),
        "box_2518" =>            Some(box_drawing::BOX_2518),
        "box_2519" =>            Some(box_drawing::BOX_2519),
        "box_251A" =>            Some(box_drawing::BOX_251A),
        "box_251B" =>            Some(box_drawing::BOX_251B),
        "box_2524" =>            Some(box_drawing::BOX_2524),
        "box_2525" =>            Some(box_drawing::BOX_2525),
        "box_2526" =>            Some(box_drawing::BOX_2526),
        "box_2527" =>            Some(box_drawing::BOX_2527),
        "box_2528" =>            Some(box_drawing::BOX_2528),
        "box_2529" =>            Some(box_drawing::BOX_2529),
        "box_252A" =>            Some(box_drawing::BOX_252A),
        "box_252B" =>            Some(box_drawing::BOX_252B),
        "box_254E" =>            Some(box_drawing::BOX_254E),
        "box_254F" =>            Some(box_drawing::BOX_254F),
        "box_2551" =>            Some(box_drawing::BOX_2551),
        "box_2555" =>            Some(box_drawing::BOX_2555),
        "box_2556" =>            Some(box_drawing::BOX_2556),
        "box_2557" =>            Some(box_drawing::BOX_2557),
        "box_255B" =>            Some(box_drawing::BOX_255B),
        "box_255C" =>            Some(box_drawing::BOX_255C),
        "box_255D" =>            Some(box_drawing::BOX_255D),
        "box_2561" =>            Some(box_drawing::BOX_2561),
        "box_2562" =>            Some(box_drawing::BOX_2562),
        "box_2563" =>            Some(box_drawing::BOX_2563),
        "box_256E" =>            Some(box_drawing::BOX_256E),
        "box_256F" =>            Some(box_drawing::BOX_256F),
        "box_2574" =>            Some(box_drawing::BOX_2574),
        "box_2575" =>            Some(box_drawing::BOX_2575),
        "box_2577" =>            Some(box_drawing::BOX_2577),
        "box_2578" =>            Some(box_drawing::BOX_2578),
        "box_2579" =>            Some(box_drawing::BOX_2579),
        "box_257B" =>            Some(box_drawing::BOX_257B),
        "box_257D" =>            Some(box_drawing::BOX_257D),
        "box_257F" =>            Some(box_drawing::BOX_257F),
        "block_258C" =>          Some(block_elements::BLOCK_258C),
        "geometric_25AA" =>      Some(geometric_shapes::GEOMETRIC_25AA),
        "geometric_25AB" =>      Some(geometric_shapes::GEOMETRIC_25AB),
        "geometric_25B4" =>      Some(geometric_shapes::GEOMETRIC_25B4),
        "geometric_25B8" =>      Some(geometric_shapes::GEOMETRIC_25B8),
        "geometric_25BE" =>      Some(geometric_shapes::GEOMETRIC_25BE),
        "geometric_25C2" =>      Some(geometric_shapes::GEOMETRIC_25C2),
        "misc_2607" =>           Some(misc_symbols::MISC_2607),
        "misc_2613" =>           Some(misc_symbols::MISC_2613),
        "misc_2628" =>           Some(misc_symbols::MISC_2628),
        "misc_263E" =>           Some(misc_symbols::MISC_263E),
        "misc_263F" =>           Some(misc_symbols::MISC_263F),
        "misc_2644" =>           Some(misc_symbols::MISC_2644),
        "misc_2647" =>           Some(misc_symbols::MISC_2647),
        "misc_266D" =>           Some(misc_symbols::MISC_266D),
        "misc_266F" =>           Some(misc_symbols::MISC_266F),
        "dingbat_2758" =>        Some(dingbats::DINGBAT_2758),
        "dingbat_2759" =>        Some(dingbats::DINGBAT_2759),
        "dingbat_275A" =>        Some(dingbats::DINGBAT_275A),
        "dingbat_2761" =>        Some(dingbats::DINGBAT_2761),
        "dingbat_27A7" =>        Some(dingbats::DINGBAT_27A7),
        "braille_2801" =>        Some(braille::BRAILLE_2801),
        "braille_2802" =>        Some(braille::BRAILLE_2802),
        "braille_2803" =>        Some(braille::BRAILLE_2803),
        "braille_2804" =>        Some(braille::BRAILLE_2804),
        "braille_2805" =>        Some(braille::BRAILLE_2805),
        "braille_2806" =>        Some(braille::BRAILLE_2806),
        "braille_2807" =>        Some(braille::BRAILLE_2807),
        "braille_2840" =>        Some(braille::BRAILLE_2840),
        "braille_2841" =>        Some(braille::BRAILLE_2841),
        "braille_2842" =>        Some(braille::BRAILLE_2842),
        "braille_2843" =>        Some(braille::BRAILLE_2843),
        "braille_2844" =>        Some(braille::BRAILLE_2844),
        "braille_2845" =>        Some(braille::BRAILLE_2845),
        "braille_2846" =>        Some(braille::BRAILLE_2846),
        "braille_2847" =>        Some(braille::BRAILLE_2847),
        "braille_2880" =>        Some(braille::BRAILLE_2880),
        "braille_2881" =>        Some(braille::BRAILLE_2881),
        "braille_2882" =>        Some(braille::BRAILLE_2882),
        "braille_2883" =>        Some(braille::BRAILLE_2883),
        "braille_2884" =>        Some(braille::BRAILLE_2884),
        "braille_2885" =>        Some(braille::BRAILLE_2885),
        "braille_2886" =>        Some(braille::BRAILLE_2886),
        "braille_2887" =>        Some(braille::BRAILLE_2887),
        "braille_28C0" =>        Some(braille::BRAILLE_28C0),
        "braille_28C1" =>        Some(braille::BRAILLE_28C1),
        "braille_28C2" =>        Some(braille::BRAILLE_28C2),
        "braille_28C3" =>        Some(braille::BRAILLE_28C3),
        "braille_28C4" =>        Some(braille::BRAILLE_28C4),
        "braille_28C5" =>        Some(braille::BRAILLE_28C5),
        "braille_28C6" =>        Some(braille::BRAILLE_28C6),
        "braille_28C7" =>        Some(braille::BRAILLE_28C7),
        _ => None,
    }
}

/// Look up a verified icon by its glyph codepoint.
#[must_use]
pub fn by_codepoint(c: char) -> Option<&'static SafeIcon> {
    UNIVERSAL_ICONS.iter().find(|icon| icon.glyph.starts_with(c))
}
