// @generated by manifest-gen — DO NOT EDIT.
//
// Every entry passed the dual-pass verification pipeline (PTY cursor
// assertions + pixel-level screenshot assertions) on ALL supported
// platform default terminals simultaneously (the CI AND gate).
use crate::SafeIcon;

pub static UNIVERSAL_ICONS: &[SafeIcon] = &[
    ascii::ASCII_0021,
    ascii::ASCII_0022,
    ascii::ASCII_0027,
    ascii::ASCII_0028,
    ascii::ASCII_0029,
    ascii::ASCII_002C,
    ascii::ASCII_002E,
    ascii::ASCII_002F,
    ascii::ASCII_003A,
    ascii::ASCII_003B,
    ascii::ASCII_003E,
    ascii::ASCII_003F,
    ascii::ASCII_0049,
    ascii::ASCII_004A,
    ascii::ASCII_005B,
    ascii::ASCII_005C,
    ascii::ASCII_005D,
    ascii::ASCII_005E,
    ascii::ASCII_0060,
    ascii::ASCII_0061,
    ascii::ASCII_0063,
    ascii::ASCII_006A,
    ascii::ASCII_0073,
    ascii::ASCII_0074,
    ascii::ASCII_007A,
    ascii::ASCII_007B,
    ascii::ASCII_007C,
    ascii::ASCII_007D,
    arrows::ARROW_21A8,
    box_drawing::BOX_2502,
    box_drawing::BOX_2503,
    box_drawing::BOX_2506,
    box_drawing::BOX_2507,
    box_drawing::BOX_250A,
    box_drawing::BOX_250B,
    box_drawing::BOX_2510,
    box_drawing::BOX_2511,
    box_drawing::BOX_2512,
    box_drawing::BOX_2513,
    box_drawing::BOX_2518,
    box_drawing::BOX_2519,
    box_drawing::BOX_251A,
    box_drawing::BOX_251B,
    box_drawing::BOX_2524,
    box_drawing::BOX_2525,
    box_drawing::BOX_2526,
    box_drawing::BOX_2527,
    box_drawing::BOX_2528,
    box_drawing::BOX_2529,
    box_drawing::BOX_252A,
    box_drawing::BOX_252B,
    box_drawing::BOX_254E,
    box_drawing::BOX_254F,
    box_drawing::BOX_2551,
    box_drawing::BOX_2555,
    box_drawing::BOX_2556,
    box_drawing::BOX_2557,
    box_drawing::BOX_255B,
    box_drawing::BOX_255C,
    box_drawing::BOX_255D,
    box_drawing::BOX_2561,
    box_drawing::BOX_2562,
    box_drawing::BOX_2563,
    box_drawing::BOX_256E,
    box_drawing::BOX_256F,
    box_drawing::BOX_2574,
    box_drawing::BOX_2575,
    box_drawing::BOX_2577,
    box_drawing::BOX_2578,
    box_drawing::BOX_2579,
    box_drawing::BOX_257B,
    box_drawing::BOX_257D,
    box_drawing::BOX_257F,
    block_elements::BLOCK_258C,
    geometric_shapes::GEOMETRIC_25AA,
    geometric_shapes::GEOMETRIC_25AB,
    geometric_shapes::GEOMETRIC_25B4,
    geometric_shapes::GEOMETRIC_25B8,
    geometric_shapes::GEOMETRIC_25BE,
    geometric_shapes::GEOMETRIC_25C2,
    misc_symbols::MISC_2607,
    misc_symbols::MISC_2613,
    misc_symbols::MISC_2628,
    misc_symbols::MISC_263E,
    misc_symbols::MISC_263F,
    misc_symbols::MISC_2644,
    misc_symbols::MISC_2647,
    misc_symbols::MISC_266D,
    misc_symbols::MISC_266F,
    dingbats::DINGBAT_2758,
    dingbats::DINGBAT_2759,
    dingbats::DINGBAT_275A,
    dingbats::DINGBAT_2761,
    dingbats::DINGBAT_27A7,
    braille::BRAILLE_2801,
    braille::BRAILLE_2802,
    braille::BRAILLE_2803,
    braille::BRAILLE_2804,
    braille::BRAILLE_2805,
    braille::BRAILLE_2806,
    braille::BRAILLE_2807,
    braille::BRAILLE_2840,
    braille::BRAILLE_2841,
    braille::BRAILLE_2842,
    braille::BRAILLE_2843,
    braille::BRAILLE_2844,
    braille::BRAILLE_2845,
    braille::BRAILLE_2846,
    braille::BRAILLE_2847,
    braille::BRAILLE_2880,
    braille::BRAILLE_2881,
    braille::BRAILLE_2882,
    braille::BRAILLE_2883,
    braille::BRAILLE_2884,
    braille::BRAILLE_2885,
    braille::BRAILLE_2886,
    braille::BRAILLE_2887,
    braille::BRAILLE_28C0,
    braille::BRAILLE_28C1,
    braille::BRAILLE_28C2,
    braille::BRAILLE_28C3,
    braille::BRAILLE_28C4,
    braille::BRAILLE_28C5,
    braille::BRAILLE_28C6,
    braille::BRAILLE_28C7,
];

pub mod ascii {
    use crate::SafeIcon;
    pub const ASCII_0021: SafeIcon = SafeIcon::new("!", "");
    pub const ASCII_0022: SafeIcon = SafeIcon::new("\"", "");
    pub const ASCII_0027: SafeIcon = SafeIcon::new("'", "");
    pub const ASCII_0028: SafeIcon = SafeIcon::new("(", "");
    pub const ASCII_0029: SafeIcon = SafeIcon::new(")", "");
    pub const ASCII_002C: SafeIcon = SafeIcon::new(",", "");
    pub const ASCII_002E: SafeIcon = SafeIcon::new(".", "");
    pub const ASCII_002F: SafeIcon = SafeIcon::new("/", "");
    pub const ASCII_003A: SafeIcon = SafeIcon::new(":", "");
    pub const ASCII_003B: SafeIcon = SafeIcon::new(";", "");
    pub const ASCII_003E: SafeIcon = SafeIcon::new(">", "");
    pub const ASCII_003F: SafeIcon = SafeIcon::new("?", "");
    pub const ASCII_0049: SafeIcon = SafeIcon::new("I", "");
    pub const ASCII_004A: SafeIcon = SafeIcon::new("J", "");
    pub const ASCII_005B: SafeIcon = SafeIcon::new("[", "");
    pub const ASCII_005C: SafeIcon = SafeIcon::new("\\", "");
    pub const ASCII_005D: SafeIcon = SafeIcon::new("]", "");
    pub const ASCII_005E: SafeIcon = SafeIcon::new("^", "");
    pub const ASCII_0060: SafeIcon = SafeIcon::new("`", "");
    pub const ASCII_0061: SafeIcon = SafeIcon::new("a", "");
    pub const ASCII_0063: SafeIcon = SafeIcon::new("c", "");
    pub const ASCII_006A: SafeIcon = SafeIcon::new("j", "");
    pub const ASCII_0073: SafeIcon = SafeIcon::new("s", "");
    pub const ASCII_0074: SafeIcon = SafeIcon::new("t", "");
    pub const ASCII_007A: SafeIcon = SafeIcon::new("z", "");
    pub const ASCII_007B: SafeIcon = SafeIcon::new("{", "");
    pub const ASCII_007C: SafeIcon = SafeIcon::new("|", "");
    pub const ASCII_007D: SafeIcon = SafeIcon::new("}", "");
}

pub mod arrows {
    use crate::SafeIcon;
    pub const ARROW_21A8: SafeIcon = SafeIcon::new("↨", "*");
}

pub mod box_drawing {
    use crate::SafeIcon;
    pub const BOX_2502: SafeIcon = SafeIcon::new("│", "|");
    pub const BOX_2503: SafeIcon = SafeIcon::new("┃", "+");
    pub const BOX_2506: SafeIcon = SafeIcon::new("┆", "+");
    pub const BOX_2507: SafeIcon = SafeIcon::new("┇", "+");
    pub const BOX_250A: SafeIcon = SafeIcon::new("┊", "+");
    pub const BOX_250B: SafeIcon = SafeIcon::new("┋", "+");
    pub const BOX_2510: SafeIcon = SafeIcon::new("┐", "+");
    pub const BOX_2511: SafeIcon = SafeIcon::new("┑", "+");
    pub const BOX_2512: SafeIcon = SafeIcon::new("┒", "+");
    pub const BOX_2513: SafeIcon = SafeIcon::new("┓", "+");
    pub const BOX_2518: SafeIcon = SafeIcon::new("┘", "+");
    pub const BOX_2519: SafeIcon = SafeIcon::new("┙", "+");
    pub const BOX_251A: SafeIcon = SafeIcon::new("┚", "+");
    pub const BOX_251B: SafeIcon = SafeIcon::new("┛", "+");
    pub const BOX_2524: SafeIcon = SafeIcon::new("┤", "+");
    pub const BOX_2525: SafeIcon = SafeIcon::new("┥", "+");
    pub const BOX_2526: SafeIcon = SafeIcon::new("┦", "+");
    pub const BOX_2527: SafeIcon = SafeIcon::new("┧", "+");
    pub const BOX_2528: SafeIcon = SafeIcon::new("┨", "+");
    pub const BOX_2529: SafeIcon = SafeIcon::new("┩", "+");
    pub const BOX_252A: SafeIcon = SafeIcon::new("┪", "+");
    pub const BOX_252B: SafeIcon = SafeIcon::new("┫", "+");
    pub const BOX_254E: SafeIcon = SafeIcon::new("╎", "+");
    pub const BOX_254F: SafeIcon = SafeIcon::new("╏", "+");
    pub const BOX_2551: SafeIcon = SafeIcon::new("║", "|");
    pub const BOX_2555: SafeIcon = SafeIcon::new("╕", "+");
    pub const BOX_2556: SafeIcon = SafeIcon::new("╖", "+");
    pub const BOX_2557: SafeIcon = SafeIcon::new("╗", "+");
    pub const BOX_255B: SafeIcon = SafeIcon::new("╛", "+");
    pub const BOX_255C: SafeIcon = SafeIcon::new("╜", "+");
    pub const BOX_255D: SafeIcon = SafeIcon::new("╝", "+");
    pub const BOX_2561: SafeIcon = SafeIcon::new("╡", "+");
    pub const BOX_2562: SafeIcon = SafeIcon::new("╢", "+");
    pub const BOX_2563: SafeIcon = SafeIcon::new("╣", "+");
    pub const BOX_256E: SafeIcon = SafeIcon::new("╮", "+");
    pub const BOX_256F: SafeIcon = SafeIcon::new("╯", "+");
    pub const BOX_2574: SafeIcon = SafeIcon::new("╴", "+");
    pub const BOX_2575: SafeIcon = SafeIcon::new("╵", "+");
    pub const BOX_2577: SafeIcon = SafeIcon::new("╷", "+");
    pub const BOX_2578: SafeIcon = SafeIcon::new("╸", "+");
    pub const BOX_2579: SafeIcon = SafeIcon::new("╹", "+");
    pub const BOX_257B: SafeIcon = SafeIcon::new("╻", "+");
    pub const BOX_257D: SafeIcon = SafeIcon::new("╽", "+");
    pub const BOX_257F: SafeIcon = SafeIcon::new("╿", "+");
}

pub mod block_elements {
    use crate::SafeIcon;
    pub const BLOCK_258C: SafeIcon = SafeIcon::new("▌", "[");
}

pub mod geometric_shapes {
    use crate::SafeIcon;
    pub const GEOMETRIC_25AA: SafeIcon = SafeIcon::new("▪", "#");
    pub const GEOMETRIC_25AB: SafeIcon = SafeIcon::new("▫", "#");
    pub const GEOMETRIC_25B4: SafeIcon = SafeIcon::new("▴", "#");
    pub const GEOMETRIC_25B8: SafeIcon = SafeIcon::new("▸", "#");
    pub const GEOMETRIC_25BE: SafeIcon = SafeIcon::new("▾", "#");
    pub const GEOMETRIC_25C2: SafeIcon = SafeIcon::new("◂", "#");
}

pub mod misc_symbols {
    use crate::SafeIcon;
    pub const MISC_2607: SafeIcon = SafeIcon::new("☇", "*");
    pub const MISC_2613: SafeIcon = SafeIcon::new("☓", "*");
    pub const MISC_2628: SafeIcon = SafeIcon::new("☨", "*");
    pub const MISC_263E: SafeIcon = SafeIcon::new("☾", "*");
    pub const MISC_263F: SafeIcon = SafeIcon::new("☿", "*");
    pub const MISC_2644: SafeIcon = SafeIcon::new("♄", "*");
    pub const MISC_2647: SafeIcon = SafeIcon::new("♇", "*");
    pub const MISC_266D: SafeIcon = SafeIcon::new("♭", "*");
    pub const MISC_266F: SafeIcon = SafeIcon::new("♯", "*");
}

pub mod dingbats {
    use crate::SafeIcon;
    pub const DINGBAT_2758: SafeIcon = SafeIcon::new("❘", "*");
    pub const DINGBAT_2759: SafeIcon = SafeIcon::new("❙", "*");
    pub const DINGBAT_275A: SafeIcon = SafeIcon::new("❚", "*");
    pub const DINGBAT_2761: SafeIcon = SafeIcon::new("❡", "*");
    pub const DINGBAT_27A7: SafeIcon = SafeIcon::new("➧", "*");
}

pub mod braille {
    use crate::SafeIcon;
    pub const BRAILLE_2801: SafeIcon = SafeIcon::new("⠁", "*");
    pub const BRAILLE_2802: SafeIcon = SafeIcon::new("⠂", "*");
    pub const BRAILLE_2803: SafeIcon = SafeIcon::new("⠃", "*");
    pub const BRAILLE_2804: SafeIcon = SafeIcon::new("⠄", "*");
    pub const BRAILLE_2805: SafeIcon = SafeIcon::new("⠅", "*");
    pub const BRAILLE_2806: SafeIcon = SafeIcon::new("⠆", "*");
    pub const BRAILLE_2807: SafeIcon = SafeIcon::new("⠇", "*");
    pub const BRAILLE_2840: SafeIcon = SafeIcon::new("⡀", "*");
    pub const BRAILLE_2841: SafeIcon = SafeIcon::new("⡁", "*");
    pub const BRAILLE_2842: SafeIcon = SafeIcon::new("⡂", "*");
    pub const BRAILLE_2843: SafeIcon = SafeIcon::new("⡃", "*");
    pub const BRAILLE_2844: SafeIcon = SafeIcon::new("⡄", "*");
    pub const BRAILLE_2845: SafeIcon = SafeIcon::new("⡅", "*");
    pub const BRAILLE_2846: SafeIcon = SafeIcon::new("⡆", "*");
    pub const BRAILLE_2847: SafeIcon = SafeIcon::new("⡇", "*");
    pub const BRAILLE_2880: SafeIcon = SafeIcon::new("⢀", "*");
    pub const BRAILLE_2881: SafeIcon = SafeIcon::new("⢁", "*");
    pub const BRAILLE_2882: SafeIcon = SafeIcon::new("⢂", "*");
    pub const BRAILLE_2883: SafeIcon = SafeIcon::new("⢃", "*");
    pub const BRAILLE_2884: SafeIcon = SafeIcon::new("⢄", "*");
    pub const BRAILLE_2885: SafeIcon = SafeIcon::new("⢅", "*");
    pub const BRAILLE_2886: SafeIcon = SafeIcon::new("⢆", "*");
    pub const BRAILLE_2887: SafeIcon = SafeIcon::new("⢇", "*");
    pub const BRAILLE_28C0: SafeIcon = SafeIcon::new("⣀", "*");
    pub const BRAILLE_28C1: SafeIcon = SafeIcon::new("⣁", "*");
    pub const BRAILLE_28C2: SafeIcon = SafeIcon::new("⣂", "*");
    pub const BRAILLE_28C3: SafeIcon = SafeIcon::new("⣃", "*");
    pub const BRAILLE_28C4: SafeIcon = SafeIcon::new("⣄", "*");
    pub const BRAILLE_28C5: SafeIcon = SafeIcon::new("⣅", "*");
    pub const BRAILLE_28C6: SafeIcon = SafeIcon::new("⣆", "*");
    pub const BRAILLE_28C7: SafeIcon = SafeIcon::new("⣇", "*");
}

/// Look up a verified icon by its catalog id (e.g. `"box_2502"`).
#[must_use]
pub fn lookup(id: &str) -> Option<SafeIcon> {
    match id {
        "ascii_0021" =>          Some(ascii::ASCII_0021),
        "ascii_0022" =>          Some(ascii::ASCII_0022),
        "ascii_0027" =>          Some(ascii::ASCII_0027),
        "ascii_0028" =>          Some(ascii::ASCII_0028),
        "ascii_0029" =>          Some(ascii::ASCII_0029),
        "ascii_002C" =>          Some(ascii::ASCII_002C),
        "ascii_002E" =>          Some(ascii::ASCII_002E),
        "ascii_002F" =>          Some(ascii::ASCII_002F),
        "ascii_003A" =>          Some(ascii::ASCII_003A),
        "ascii_003B" =>          Some(ascii::ASCII_003B),
        "ascii_003E" =>          Some(ascii::ASCII_003E),
        "ascii_003F" =>          Some(ascii::ASCII_003F),
        "ascii_0049" =>          Some(ascii::ASCII_0049),
        "ascii_004A" =>          Some(ascii::ASCII_004A),
        "ascii_005B" =>          Some(ascii::ASCII_005B),
        "ascii_005C" =>          Some(ascii::ASCII_005C),
        "ascii_005D" =>          Some(ascii::ASCII_005D),
        "ascii_005E" =>          Some(ascii::ASCII_005E),
        "ascii_0060" =>          Some(ascii::ASCII_0060),
        "ascii_0061" =>          Some(ascii::ASCII_0061),
        "ascii_0063" =>          Some(ascii::ASCII_0063),
        "ascii_006A" =>          Some(ascii::ASCII_006A),
        "ascii_0073" =>          Some(ascii::ASCII_0073),
        "ascii_0074" =>          Some(ascii::ASCII_0074),
        "ascii_007A" =>          Some(ascii::ASCII_007A),
        "ascii_007B" =>          Some(ascii::ASCII_007B),
        "ascii_007C" =>          Some(ascii::ASCII_007C),
        "ascii_007D" =>          Some(ascii::ASCII_007D),
        "arrow_21A8" =>          Some(arrows::ARROW_21A8),
        "box_2502" =>            Some(box_drawing::BOX_2502),
        "box_2503" =>            Some(box_drawing::BOX_2503),
        "box_2506" =>            Some(box_drawing::BOX_2506),
        "box_2507" =>            Some(box_drawing::BOX_2507),
        "box_250A" =>            Some(box_drawing::BOX_250A),
        "box_250B" =>            Some(box_drawing::BOX_250B),
        "box_2510" =>            Some(box_drawing::BOX_2510),
        "box_2511" =>            Some(box_drawing::BOX_2511),
        "box_2512" =>            Some(box_drawing::BOX_2512),
        "box_2513" =>            Some(box_drawing::BOX_2513),
        "box_2518" =>            Some(box_drawing::BOX_2518),
        "box_2519" =>            Some(box_drawing::BOX_2519),
        "box_251A" =>            Some(box_drawing::BOX_251A),
        "box_251B" =>            Some(box_drawing::BOX_251B),
        "box_2524" =>            Some(box_drawing::BOX_2524),
        "box_2525" =>            Some(box_drawing::BOX_2525),
        "box_2526" =>            Some(box_drawing::BOX_2526),
        "box_2527" =>            Some(box_drawing::BOX_2527),
        "box_2528" =>            Some(box_drawing::BOX_2528),
        "box_2529" =>            Some(box_drawing::BOX_2529),
        "box_252A" =>            Some(box_drawing::BOX_252A),
        "box_252B" =>            Some(box_drawing::BOX_252B),
        "box_254E" =>            Some(box_drawing::BOX_254E),
        "box_254F" =>            Some(box_drawing::BOX_254F),
        "box_2551" =>            Some(box_drawing::BOX_2551),
        "box_2555" =>            Some(box_drawing::BOX_2555),
        "box_2556" =>            Some(box_drawing::BOX_2556),
        "box_2557" =>            Some(box_drawing::BOX_2557),
        "box_255B" =>            Some(box_drawing::BOX_255B),
        "box_255C" =>            Some(box_drawing::BOX_255C),
        "box_255D" =>            Some(box_drawing::BOX_255D),
        "box_2561" =>            Some(box_drawing::BOX_2561),
        "box_2562" =>            Some(box_drawing::BOX_2562),
        "box_2563" =>            Some(box_drawing::BOX_2563),
        "box_256E" =>            Some(box_drawing::BOX_256E),
        "box_256F" =>            Some(box_drawing::BOX_256F),
        "box_2574" =>            Some(box_drawing::BOX_2574),
        "box_2575" =>            Some(box_drawing::BOX_2575),
        "box_2577" =>            Some(box_drawing::BOX_2577),
        "box_2578" =>            Some(box_drawing::BOX_2578),
        "box_2579" =>            Some(box_drawing::BOX_2579),
        "box_257B" =>            Some(box_drawing::BOX_257B),
        "box_257D" =>            Some(box_drawing::BOX_257D),
        "box_257F" =>            Some(box_drawing::BOX_257F),
        "block_258C" =>          Some(block_elements::BLOCK_258C),
        "geometric_25AA" =>      Some(geometric_shapes::GEOMETRIC_25AA),
        "geometric_25AB" =>      Some(geometric_shapes::GEOMETRIC_25AB),
        "geometric_25B4" =>      Some(geometric_shapes::GEOMETRIC_25B4),
        "geometric_25B8" =>      Some(geometric_shapes::GEOMETRIC_25B8),
        "geometric_25BE" =>      Some(geometric_shapes::GEOMETRIC_25BE),
        "geometric_25C2" =>      Some(geometric_shapes::GEOMETRIC_25C2),
        "misc_2607" =>           Some(misc_symbols::MISC_2607),
        "misc_2613" =>           Some(misc_symbols::MISC_2613),
        "misc_2628" =>           Some(misc_symbols::MISC_2628),
        "misc_263E" =>           Some(misc_symbols::MISC_263E),
        "misc_263F" =>           Some(misc_symbols::MISC_263F),
        "misc_2644" =>           Some(misc_symbols::MISC_2644),
        "misc_2647" =>           Some(misc_symbols::MISC_2647),
        "misc_266D" =>           Some(misc_symbols::MISC_266D),
        "misc_266F" =>           Some(misc_symbols::MISC_266F),
        "dingbat_2758" =>        Some(dingbats::DINGBAT_2758),
        "dingbat_2759" =>        Some(dingbats::DINGBAT_2759),
        "dingbat_275A" =>        Some(dingbats::DINGBAT_275A),
        "dingbat_2761" =>        Some(dingbats::DINGBAT_2761),
        "dingbat_27A7" =>        Some(dingbats::DINGBAT_27A7),
        "braille_2801" =>        Some(braille::BRAILLE_2801),
        "braille_2802" =>        Some(braille::BRAILLE_2802),
        "braille_2803" =>        Some(braille::BRAILLE_2803),
        "braille_2804" =>        Some(braille::BRAILLE_2804),
        "braille_2805" =>        Some(braille::BRAILLE_2805),
        "braille_2806" =>        Some(braille::BRAILLE_2806),
        "braille_2807" =>        Some(braille::BRAILLE_2807),
        "braille_2840" =>        Some(braille::BRAILLE_2840),
        "braille_2841" =>        Some(braille::BRAILLE_2841),
        "braille_2842" =>        Some(braille::BRAILLE_2842),
        "braille_2843" =>        Some(braille::BRAILLE_2843),
        "braille_2844" =>        Some(braille::BRAILLE_2844),
        "braille_2845" =>        Some(braille::BRAILLE_2845),
        "braille_2846" =>        Some(braille::BRAILLE_2846),
        "braille_2847" =>        Some(braille::BRAILLE_2847),
        "braille_2880" =>        Some(braille::BRAILLE_2880),
        "braille_2881" =>        Some(braille::BRAILLE_2881),
        "braille_2882" =>        Some(braille::BRAILLE_2882),
        "braille_2883" =>        Some(braille::BRAILLE_2883),
        "braille_2884" =>        Some(braille::BRAILLE_2884),
        "braille_2885" =>        Some(braille::BRAILLE_2885),
        "braille_2886" =>        Some(braille::BRAILLE_2886),
        "braille_2887" =>        Some(braille::BRAILLE_2887),
        "braille_28C0" =>        Some(braille::BRAILLE_28C0),
        "braille_28C1" =>        Some(braille::BRAILLE_28C1),
        "braille_28C2" =>        Some(braille::BRAILLE_28C2),
        "braille_28C3" =>        Some(braille::BRAILLE_28C3),
        "braille_28C4" =>        Some(braille::BRAILLE_28C4),
        "braille_28C5" =>        Some(braille::BRAILLE_28C5),
        "braille_28C6" =>        Some(braille::BRAILLE_28C6),
        "braille_28C7" =>        Some(braille::BRAILLE_28C7),
        _ => None,
    }
}

/// Look up a verified icon by its glyph codepoint.
#[must_use]
pub fn by_codepoint(c: char) -> Option<&'static SafeIcon> {
    UNIVERSAL_ICONS.iter().find(|icon| icon.glyph.starts_with(c))
}
